//Set Jobs
export const FETCHING_ALL_SET_JOBS = 'FETCHING_ALL_SET_JOBS';
export const FETCHING_ALL_SET_JOBS_COMPLETE = 'FETCHING_ALL_SET_JOBS_COMPLETE';
export const FETCHING_ALL_SET_JOBS_FAIL = 'FETCHING_ALL_SET_JOBS_FAIL';
export const UPDATE_SET_JOBS = 'UPDATE_SET_JOBS';
export const UPDATE_SCREEN_KEY = 'UPDATE_SCREEN_KEY';
//Calendar
export const UPDATE_CALENDAR_SELECTED = 'UPDATE_CALENDAR_SELECTED';
//Remove Jobs
export const REMOVING_JOB = 'REMOVING_JOB';
export const REMOVE_JOB_SUCCESS = 'REMOVE_JOB_SUCCESS';
export const REMOVE_JOB_FAIL = 'REMOVE_JOB_FAIL';
//employees
export const FETCHING_ALL_EMPLOYEES = 'FETCHING_ALL_EMPLOYEES';
export const FETCHING_ALL_EMPLOYEES_SUCCESS = 'FETCHING_ALL_EMPLOYEES_SUCCESS';
export const FETCHING_ALL_EMPLOYEES_FAIL = 'FETCHING_ALL_EMPLOYEES_FAIL';
export const REMOVING_EMPLOYEE = 'REMOVING_EMPLOYEE';
export const REMOVE_EMPLOYEE_SUCCESS = 'REMOVE_EMPLOYEE_SUCCESS';
export const REMOVE_EMPLOYEE_FAIL = 'REMOVE_EMPLOYEE_FAIL';
//clients
export const FETCHING_ALL_CLIENTS = 'FETCHING_ALL_CLIENTS';
export const FETCHING_ALL_CLIENTS_SUCCESS = 'FETCHING_ALL_CLIENTS_SUCCESS';
export const FETCHING_ALL_CLIENTS_FAIL = 'FETCHING_ALL_CLIENTS_FAIL';
export const REMOVING_CLIENT = 'REMOVING_CLIENT';
export const REMOVE_CLIENT_SUCCESS = 'REMOVE_CLIENT_SUCCESS';
export const REMOVE_CLIENT_FAIL = 'REMOVE_CLIENT_FAIL';
//create Jobs
export const UPDATE_SELECT_TEMPLATE_SCREEN_KEY = 'UPDATE_SELECT_TEMPLATE_SCREEN_KEU';
export const SET_NEW_JOB_CLIENT = 'SET_NEW_JOB_CLIENT';
export const SET_NEW_JOB_TASK = 'SET_NEW_JOB_TASK';
export const UNSET_NEW_JOB_TASK = 'UNSET_NEW_JOB_TASK';
export const UPDATE_SELECT_TASK_SCREEN_KEY = 'UPDATE_SELECT_TASK_SCREEN_KEY';
export const SET_NEW_JOB_EMPLOYEE = 'SET_NEW_JOB_EMPLOYEE';
export const UNSET_NEW_JOB_EMPLOYEE = 'UNSET_NEW_JOB_EMPLOYEE';
export const UPDATE_SELECT_EMPLOYEE_SCREEN_KEY = 'UPDATE_SELECT_EMPLOYEE_SCREEN_KEY';
export const SET_NEW_JOB_TITLE = 'SET_NEW_JOB_TITLE';
export const SET_NEW_JOB_COMMENT = 'SET_NEW_JOB_COMMENT';
export const UPDATE_SET_TITLE_AND_COMMENT_SCREEN_KEY = 'UPDATE_SET_TITLE_AND_COMMENT_SCREEN_KEY';
export const INITIATING_NEW_JOB = 'INITIATING_NEW_JOB';
export const INITIATE_NEW_JOB_SUCCESS = 'INITIATE_NEW_JOB_SUCCESS';
export const INITIATE_NEW_JOB_FAIL = 'INITIATE_NEW_JOB_FAIL';
export const RESET_NEW_JOB_DATA = 'RESET_NEW_JOB_DATA';
//tasks
export const FETCHING_ALL_TASKS = 'FETCHING_ALL_TASKS';
export const FETCH_ALL_TASKS_SUCCESS = 'FETCH_ALL_TASKS_SUCCESS';
export const FETCH_ALL_TASKS_FAIL = 'FETCH_ALL_TASKS_FAIL';
export const CREATING_NEW_TASK = 'CREATING_NEW_TASK';
export const CREATE_NEW_TASK_SUCCESS = 'CREATE_NEW_TASK_SUCCESS';
export const CREATE_NEW_TASK_FAIL = 'CREATE_NEW_TASK_FAIL';
export const REMOVING_TASK = 'REMOVING_TASK';
export const REMOVE_TASK_SUCCESS = 'REMOVE_TASK_SUCCESS';
export const REMOVE_TASK_FAIL = 'REMOVE_TASK_FAIL';
