//Set Jobs
export const FETCHING_ALL_SET_JOBS = 'FETCHING_ALL_SET_JOBS';
export const FETCHING_ALL_SET_JOBS_COMPLETE = 'FETCHING_ALL_SET_JOBS_COMPLETE';
export const FETCHING_ALL_SET_JOBS_FAIL = 'FETCHING_ALL_SET_JOBS_FAIL';
export const UPDATE_SET_JOBS = 'UPDATE_SET_JOBS';
//Calendar
export const UPDATE_CALENDAR_SELECTED = 'UPDATE_CALENDAR_SELECTED';
//CRUD Jobs
export const REMOVING_JOB = 'REMOVING_JOB';
export const REMOVE_JOB_SUCCESS = 'REMOVE_JOB_SUCCESS';
export const REMOVE_JOB_FAIL = 'REMOVE_JOB_FAIL';
