//Set Jobs
export const FETCHING_ALL_SET_JOBS = 'FETCHING_ALL_SET_JOBS';
export const FETCHING_ALL_SET_JOBS_COMPLETE = 'FETCHING_ALL_SET_JOBS_COMPLETE';
export const FETCHING_ALL_SET_JOBS_FAIL = 'FETCHING_ALL_SET_JOBS_FAIL';
export const UPDATE_SET_JOBS = 'UPDATE_SET_JOBS';
export const UPDATE_SCREEN_KEY = 'UPDATE_SCREEN_KEY';
//Calendar
export const UPDATE_CALENDAR_SELECTED = 'UPDATE_CALENDAR_SELECTED';
//CRUD Jobs
export const REMOVING_JOB = 'REMOVING_JOB';
export const REMOVE_JOB_SUCCESS = 'REMOVE_JOB_SUCCESS';
export const REMOVE_JOB_FAIL = 'REMOVE_JOB_FAIL';
//employees
export const FETCHING_ALL_EMPLOYEES = 'FETCHING_ALL_EMPLOYEES';
export const FETCHING_ALL_EMPLOYEES_SUCCESS = 'FETCHING_ALL_EMPLOYEES_SUCCESS';
export const FETCHING_ALL_EMPLOYEES_FAIL = 'FETCHING_ALL_EMPLOYEES_FAIL';
export const REMOVING_EMPLOYEE = 'REMOVING_EMPLOYEE';
export const REMOVE_EMPLOYEE_SUCCESS = 'REMOVE_EMPLOYEE_SUCCESS';
export const REMOVE_EMPLOYEE_FAIL = 'REMOVE_EMPLOYEE_FAIL';
//clients
export const FETCHING_ALL_CLIENTS = 'FETCHING_ALL_CLIENTS';
export const FETCHING_ALL_CLIENTS_SUCCESS = 'FETCHING_ALL_CLIENTS_SUCCESS';
export const FETCHING_ALL_CLIENTS_FAIL = 'FETCHING_ALL_CLIENTS_FAIL';
export const REMOVING_CLIENT = 'REMOVING_CLIENT';
export const REMOVE_CLIENT_SUCCESS = 'REMOVE_CLIENT_SUCCESS';
export const REMOVE_CLIENT_FAIL = 'REMOVE_CLIENT_FAIL';
